[package]
name = "diagnostics"
authors = { workspace = true }
categories = { workspace = true }
edition = { workspace = true }
version = { workspace = true }

[dependencies]
colored = "2.0.4"
serde = { version = "1.0.188", features = ["derive"] }
strum = "0.25"
strum_macros = "0.25"
