[workspace]
members = [
  "crates/diagnostics",
  "crates/interpreter",
  "crates/lexer",
  "crates/parser",
]

[workspace.package]
authors = ["Timo Behrend"]
categories = ["interpreter", "toy-language", "arkoi"]
edition = "2021"
version = "0.1.0"
