[package]
name = "lexer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diagnostics = { path = "../diagnostics" }
insta = { version = "1.31.0", features = ["yaml"] }
serde = { version = "1.0.188", features = ["derive"] }
